# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proyecto < Formula
  desc "Proyecto is a lightweight CLI tool for managing local projects"
  homepage "https://github.com/robertwang1001/proyecto"
  version "2.5.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robertwang1001/proyecto/releases/download/v2.5.7/proyecto_2.5.7_darwin_amd64.tar.gz"
      sha256 "012f75b54abadda26b51f0ab929c986906b55dc8cce804840816210d78a48d20"

      define_method(:install) do
        bin.install "proyecto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robertwang1001/proyecto/releases/download/v2.5.7/proyecto_2.5.7_darwin_arm64.tar.gz"
      sha256 "e8b631e621ef7b580c45dfa7a200aa09c2027107d9a06c5873f598ca7f856494"

      define_method(:install) do
        bin.install "proyecto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robertwang1001/proyecto/releases/download/v2.5.7/proyecto_2.5.7_linux_amd64.tar.gz"
      sha256 "4fbaaa46150154784c548766ff465189352bfd0e36aa2b90505ce4e82c7e7027"
      define_method(:install) do
        bin.install "proyecto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robertwang1001/proyecto/releases/download/v2.5.7/proyecto_2.5.7_linux_arm64.tar.gz"
      sha256 "042ff86cd3e7df8b58e3b0c3dcf5bbe4223cbaecf5ede4e4e3af4c96a830c0b4"
      define_method(:install) do
        bin.install "proyecto"
      end
    end
  end

  def caveats
    <<~EOS
      proyecto --help
    EOS
  end

  test do
    system "#{bin}/proyecto --version"
  end
end
