# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updown < Formula
  desc "A CLI tool to upload or download files to or from GitHub Gist"
  homepage "https://github.com/robertwang1001/updown"
  version "1.7.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robertwang1001/updown/releases/download/v1.7.4/updown_1.7.4_darwin_amd64.tar.gz"
      sha256 "ec85c849c8f5c4960c5dcbf5288b572838b4e0385a98f068526e292dd2fcdd18"

      define_method(:install) do
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robertwang1001/updown/releases/download/v1.7.4/updown_1.7.4_darwin_arm64.tar.gz"
      sha256 "9ecbb6ac7423d8435ab91fa99d164a6aea6bf35b818ce7238e45272777d7d61c"

      define_method(:install) do
        bin.install "updown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robertwang1001/updown/releases/download/v1.7.4/updown_1.7.4_linux_amd64.tar.gz"
      sha256 "c759fb11a06888f64f2a765fd141bcd77a38d69fb5816bb716ea06de3fb9413a"
      define_method(:install) do
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robertwang1001/updown/releases/download/v1.7.4/updown_1.7.4_linux_arm64.tar.gz"
      sha256 "53a51fe5e03ec187f83369402f8eed7895ce54638cd3d4ba046c2d8fbdc3a014"
      define_method(:install) do
        bin.install "updown"
      end
    end
  end

  def post_install
    # Ensure the ~/.updown/logs directory exists
    (Pathname.new(Dir.home)/".updown/logs").mkpath
  end

  def caveats
    <<~EOS
      updown --help
    EOS
  end

  service do
    run [opt_bin/"updown", "upload", "--quiet", "--notify"]
    run_type :cron
    cron "0 15 * * *" # 15:00 every day
    log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.log"
    error_log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.error.log"
    environment_variables PATH: std_service_path_env
  end

  test do
    system "#{bin}/updown --version"
  end
end
