# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updown < Formula
  desc "A CLI tool to upload or download files to or from GitHub Gist"
  homepage "https://github.com/robertwang1001/updown"
  version "1.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robertwang1001/updown/releases/download/v1.7.3/updown_1.7.3_darwin_amd64.tar.gz"
      sha256 "a88985c4a775fff176d5e4d8bb49bb13771fc18f26401a5ce95554d3207b4358"

      define_method(:install) do
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robertwang1001/updown/releases/download/v1.7.3/updown_1.7.3_darwin_arm64.tar.gz"
      sha256 "e71ecb29f8df513ee269c1433e1bfeec2c5819f9c6725afeb74040d30bae8c9e"

      define_method(:install) do
        bin.install "updown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robertwang1001/updown/releases/download/v1.7.3/updown_1.7.3_linux_amd64.tar.gz"
      sha256 "eb2b44368b06208888d6ec45f6735911bb7679549da847a92041b531491dfb6d"
      define_method(:install) do
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robertwang1001/updown/releases/download/v1.7.3/updown_1.7.3_linux_arm64.tar.gz"
      sha256 "0e163647e66964f24010161069eb3e61b32bae7c2c429d994ff807c7d4de2b29"
      define_method(:install) do
        bin.install "updown"
      end
    end
  end

  def post_install
    # Ensure the ~/.updown/logs directory exists
    (Pathname.new(Dir.home)/".updown/logs").mkpath
  end

  def caveats
    <<~EOS
      updown --help
    EOS
  end

  service do
    run [opt_bin/"updown", "upload", "--quiet", "--notify"]
    run_type :cron
    cron "0 15 * * *" # 15:00 every day
    log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.log"
    error_log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.error.log"
    environment_variables PATH: std_service_path_env
  end

  test do
    system "#{bin}/updown --version"
  end
end
